FROM node:18-alpine

WORKDIR /youtube-backend

COPY package.json package-lock.json ./

RUN npm ci --only=production

COPY . .

RUN addgroup appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 8000

CMD ["npm", "start"]